###########################################################
## SSH Key Transfer Script                               ##
## Transfers SSH Keys generated by ssh-keygen            ##
## Will transfer keys from default ssh key location      ## 
## c:\Users\USERNAME\.ssh                                ##
###########################################################

$Server = Read-Host -Prompt 'Input your IP or FQDN:'
type $env:USERPROFILE\.ssh\id_rsa.pub | ssh $Server "cat >> .ssh/authorized_keys"
